

name: Run it on action

on:
  push:
    branches:
      - master
  schedule:
    - cron: 26 16 * * 5
jobs:
  run-it:
    runs-on: ubuntu-18.04
    name: Run it on action
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
      - name: Setup Cloud flare WARP
        run: |
          sudo bash <(curl -fsSL git.io/warp.sh) d        
      - name: get ip info
        run: |
          sudo curl -i test.ipw.cn
